# Generated by Django 5.1.2 on 2024-10-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('job_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('deliv_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
